// ============================================================
// Campus Pass by VinkU — Catálogo mock de instituciones aliadas
// Cursos de extensión / educación continua reales o verosímiles de
// 4 aliadas: IUMAFIS, Católica del Norte (UCN), Visión de las Américas
// y Universidad de La Sabana.
//
// NOTA: los precios (precio_publico_cop / precio_vinku_cop) son ESTIMADOS
// de referencia — ajústalos con los valores reales de convenio desde el
// panel Universidad → Campus Pass. Los nombres de cursos provienen de la
// oferta pública de educación continua de cada institución.
// ============================================================

import type { Curso } from "../types/etapa1";

export const CATALOGO_MOCK: Curso[] = [
  // ---------- IUMAFIS — Bello, Antioquia ----------
  {
    id_curso: "iumafis-sst",
    institucion: "IUMAFIS - Inst. Univ. Marco Fidel Suárez",
    tipo_institucion: "universidad",
    nombre_curso: "Diplomado en Seguridad y Salud en el Trabajo",
    nivel: "diplomado",
    modalidad: "hibrida",
    duracion_horas: 120,
    duracion_semanas: 12,
    precio_publico_cop: 1600000,
    precio_vinku_cop: 1050000,
    descuento_disponible: true,
    ciudad: "Bello",
    habilidades_que_desarrolla: ["SST", "seguridad laboral", "gestión de riesgos", "normatividad"],
    roles_que_habilita: ["Coordinador SST", "Analista de Seguridad y Salud en el Trabajo"],
    prerequisitos: [],
    cupos_disponibles: 25,
    proxima_fecha_inicio: "2026-08-11",
    categoria: "Salud ocupacional y SST",
    palabras_clave: ["sst", "seguridad", "salud ocupacional"],
    activo: true,
  },
  {
    id_curso: "iumafis-excel",
    institucion: "IUMAFIS - Inst. Univ. Marco Fidel Suárez",
    tipo_institucion: "universidad",
    nombre_curso: "Curso de Excel para la Gestión Administrativa",
    nivel: "educacion_continua",
    modalidad: "virtual",
    duracion_horas: 48,
    duracion_semanas: 6,
    precio_publico_cop: 720000,
    precio_vinku_cop: 460000,
    descuento_disponible: true,
    ciudad: "Bello",
    habilidades_que_desarrolla: ["digitales", "excel", "datos", "ofimática"],
    roles_que_habilita: ["Auxiliar Administrativo", "Asistente de Datos", "Primera Carrera Real"],
    prerequisitos: [],
    cupos_disponibles: 40,
    proxima_fecha_inicio: "2026-07-14",
    categoria: "Gestión administrativa y finanzas",
    palabras_clave: ["excel", "administración", "ofimática"],
    activo: true,
  },
  {
    id_curso: "iumafis-talento",
    institucion: "IUMAFIS - Inst. Univ. Marco Fidel Suárez",
    tipo_institucion: "universidad",
    nombre_curso: "Diplomado en Gestión del Talento Humano",
    nivel: "diplomado",
    modalidad: "hibrida",
    duracion_horas: 100,
    duracion_semanas: 10,
    precio_publico_cop: 1400000,
    precio_vinku_cop: 920000,
    descuento_disponible: true,
    ciudad: "Bello",
    habilidades_que_desarrolla: ["gestión de personas", "liderazgo", "comunicación", "selección de personal"],
    roles_que_habilita: ["Coordinador de Talento", "Gestor de Personas", "Líder de Equipo"],
    prerequisitos: [],
    cupos_disponibles: 20,
    proxima_fecha_inicio: "2026-08-04",
    categoria: "Liderazgo y gestión de personas",
    palabras_clave: ["talento", "rrhh", "gestión humana"],
    activo: true,
  },

  // ---------- Católica del Norte (UCN) — 100% virtual ----------
  {
    id_curso: "ucn-ciberseguridad",
    institucion: "Católica del Norte Fundación Universitaria",
    tipo_institucion: "universidad",
    nombre_curso: "Diplomado en Ciberseguridad",
    nivel: "diplomado",
    modalidad: "virtual",
    duracion_horas: 120,
    duracion_semanas: 12,
    precio_publico_cop: 1500000,
    precio_vinku_cop: 980000,
    descuento_disponible: true,
    ciudad: "Medellín",
    habilidades_que_desarrolla: ["ciberseguridad", "digitales", "seguridad de la información", "gestión de riesgos"],
    roles_que_habilita: ["Analista de Ciberseguridad", "Tech sin Título", "Analista de Seguridad Informática"],
    prerequisitos: [],
    cupos_disponibles: 35,
    proxima_fecha_inicio: "2026-07-21",
    categoria: "Tecnología y sistemas",
    palabras_clave: ["ciberseguridad", "seguridad", "ti", "tech"],
    activo: true,
  },
  {
    id_curso: "ucn-gestion-financiera",
    institucion: "Católica del Norte Fundación Universitaria",
    tipo_institucion: "universidad",
    nombre_curso: "Diplomado en Gestión Financiera",
    nivel: "diplomado",
    modalidad: "virtual",
    duracion_horas: 144,
    duracion_semanas: 14,
    precio_publico_cop: 1700000,
    precio_vinku_cop: 1120000,
    descuento_disponible: true,
    ciudad: "Medellín",
    habilidades_que_desarrolla: ["finanzas", "análisis financiero", "datos", "planeación"],
    roles_que_habilita: ["Analista Financiero", "Coordinador Administrativo y Financiero"],
    prerequisitos: [],
    cupos_disponibles: 30,
    proxima_fecha_inicio: "2026-08-18",
    categoria: "Gestión administrativa y finanzas",
    palabras_clave: ["finanzas", "financiera", "presupuesto"],
    activo: true,
  },
  {
    id_curso: "ucn-docencia",
    institucion: "Católica del Norte Fundación Universitaria",
    tipo_institucion: "universidad",
    nombre_curso: "Diplomado en Docencia Universitaria",
    nivel: "diplomado",
    modalidad: "virtual",
    duracion_horas: 120,
    duracion_semanas: 12,
    precio_publico_cop: 1450000,
    precio_vinku_cop: 950000,
    descuento_disponible: true,
    ciudad: "Medellín",
    habilidades_que_desarrolla: ["docencia", "diseño instruccional", "formación", "comunicación"],
    roles_que_habilita: ["Arquitecto del Aprendizaje", "Docente Universitario", "Líder de Formación"],
    prerequisitos: ["Pregrado culminado"],
    cupos_disponibles: 28,
    proxima_fecha_inicio: "2026-07-28",
    categoria: "Liderazgo y gestión de personas",
    palabras_clave: ["docencia", "formación", "aprendizaje"],
    activo: true,
  },

  // ---------- Visión de las Américas — Medellín ----------
  {
    id_curso: "uam-sst",
    institucion: "Inst. Univ. Visión de las Américas",
    tipo_institucion: "universidad",
    nombre_curso: "Diplomado en Seguridad y Salud en el Trabajo",
    nivel: "diplomado",
    modalidad: "hibrida",
    duracion_horas: 132,
    duracion_semanas: 13,
    precio_publico_cop: 1800000,
    precio_vinku_cop: 1180000,
    descuento_disponible: true,
    ciudad: "Medellín",
    habilidades_que_desarrolla: ["SST", "salud ocupacional", "gestión de riesgos", "normatividad"],
    roles_que_habilita: ["Coordinador SST", "Auditor en Salud Ocupacional"],
    prerequisitos: [],
    cupos_disponibles: 22,
    proxima_fecha_inicio: "2026-08-25",
    categoria: "Salud ocupacional y SST",
    palabras_clave: ["sst", "salud", "seguridad laboral"],
    activo: true,
  },
  {
    id_curso: "uam-auditoria-salud",
    institucion: "Inst. Univ. Visión de las Américas",
    tipo_institucion: "universidad",
    nombre_curso: "Diplomado en Auditoría en Salud",
    nivel: "diplomado",
    modalidad: "virtual",
    duracion_horas: 120,
    duracion_semanas: 12,
    precio_publico_cop: 2100000,
    precio_vinku_cop: 0,
    descuento_disponible: false,
    ciudad: "Medellín",
    habilidades_que_desarrolla: ["auditoría", "salud", "normatividad", "gestión de calidad"],
    roles_que_habilita: ["Auditor en Salud", "Coordinador de Calidad en Salud"],
    prerequisitos: ["Pregrado en áreas de la salud o administración"],
    cupos_disponibles: 18,
    proxima_fecha_inicio: "2026-09-01",
    categoria: "Salud ocupacional y SST",
    palabras_clave: ["auditoría", "salud", "calidad"],
    activo: true,
  },
  {
    id_curso: "uam-marketing",
    institucion: "Inst. Univ. Visión de las Américas",
    tipo_institucion: "universidad",
    nombre_curso: "Curso de Marketing Digital y Redes Sociales",
    nivel: "educacion_continua",
    modalidad: "virtual",
    duracion_horas: 60,
    duracion_semanas: 8,
    precio_publico_cop: 980000,
    precio_vinku_cop: 640000,
    descuento_disponible: true,
    ciudad: "Medellín",
    habilidades_que_desarrolla: ["marketing", "comunicación", "redes sociales", "growth"],
    roles_que_habilita: ["Estratega de Marca", "Community Manager", "Coordinador de Marketing"],
    prerequisitos: [],
    cupos_disponibles: 32,
    proxima_fecha_inicio: "2026-07-16",
    categoria: "Marketing y ventas",
    palabras_clave: ["marketing", "redes sociales", "marca"],
    activo: true,
  },

  // ---------- Universidad de La Sabana — Chía / Bogotá ----------
  {
    id_curso: "sabana-pmp",
    institucion: "Universidad de La Sabana",
    tipo_institucion: "universidad",
    nombre_curso: "Diplomado en Gerencia de Proyectos con Preparación para el Examen PMP",
    nivel: "diplomado",
    modalidad: "hibrida",
    duracion_horas: 160,
    duracion_semanas: 16,
    precio_publico_cop: 5200000,
    precio_vinku_cop: 3900000,
    descuento_disponible: true,
    ciudad: "Chía",
    habilidades_que_desarrolla: ["gestión de proyectos", "liderazgo", "planeación estratégica", "pmp"],
    roles_que_habilita: ["Líder de Proyecto", "Gerente de Proyecto", "Coordinador de equipo"],
    prerequisitos: ["Pregrado culminado", "Experiencia en proyectos"],
    cupos_disponibles: 15,
    proxima_fecha_inicio: "2026-08-19",
    categoria: "Liderazgo y gestión de personas",
    palabras_clave: ["proyectos", "pmp", "gerencia", "liderazgo"],
    activo: true,
  },
  {
    id_curso: "sabana-ia",
    institucion: "Universidad de La Sabana",
    tipo_institucion: "universidad",
    nombre_curso: "Diplomado en Inteligencia Artificial Aplicada",
    nivel: "diplomado",
    modalidad: "virtual",
    duracion_horas: 120,
    duracion_semanas: 12,
    precio_publico_cop: 4200000,
    precio_vinku_cop: 0,
    descuento_disponible: false,
    ciudad: "Chía",
    habilidades_que_desarrolla: ["inteligencia artificial", "datos", "digitales", "analítica"],
    roles_que_habilita: ["Analista de Datos", "Especialista en IA", "Tech sin Título"],
    prerequisitos: [],
    cupos_disponibles: 20,
    proxima_fecha_inicio: "2026-09-08",
    categoria: "Tecnología y sistemas",
    palabras_clave: ["ia", "inteligencia artificial", "datos"],
    activo: true,
  },
  {
    id_curso: "sabana-coaching",
    institucion: "Universidad de La Sabana",
    tipo_institucion: "universidad",
    nombre_curso: "Diplomado en Coaching y Liderazgo Educativo",
    nivel: "diplomado",
    modalidad: "virtual",
    duracion_horas: 110,
    duracion_semanas: 11,
    precio_publico_cop: 3800000,
    precio_vinku_cop: 2700000,
    descuento_disponible: true,
    ciudad: "Chía",
    habilidades_que_desarrolla: ["liderazgo", "coaching", "gestión de personas", "comunicación"],
    roles_que_habilita: ["Líder de Equipo", "Coordinador", "Gestor de Personas"],
    prerequisitos: [],
    cupos_disponibles: 18,
    proxima_fecha_inicio: "2026-08-12",
    categoria: "Liderazgo y gestión de personas",
    palabras_clave: ["coaching", "liderazgo", "educativo"],
    activo: true,
  },
  {
    id_curso: "sabana-innovacion",
    institucion: "Universidad de La Sabana",
    tipo_institucion: "universidad",
    nombre_curso: "Diplomado en Innovación y Sostenibilidad",
    nivel: "diplomado",
    modalidad: "virtual",
    duracion_horas: 100,
    duracion_semanas: 10,
    precio_publico_cop: 3600000,
    precio_vinku_cop: 2600000,
    descuento_disponible: true,
    ciudad: "Chía",
    habilidades_que_desarrolla: ["innovación", "sostenibilidad", "estrategia", "digitales"],
    roles_que_habilita: ["Líder de Innovación", "Analista de Negocio", "Estratega de Marca"],
    prerequisitos: [],
    cupos_disponibles: 24,
    proxima_fecha_inicio: "2026-07-29",
    categoria: "Marketing y ventas",
    palabras_clave: ["innovación", "sostenibilidad", "estrategia"],
    activo: true,
  },
  {
    id_curso: "sabana-dua",
    institucion: "Universidad de La Sabana",
    tipo_institucion: "universidad",
    nombre_curso: "Diplomado en Diseño Universal para el Aprendizaje y Educación Inclusiva",
    nivel: "diplomado",
    modalidad: "virtual",
    duracion_horas: 96,
    duracion_semanas: 10,
    precio_publico_cop: 3400000,
    precio_vinku_cop: 2450000,
    descuento_disponible: true,
    ciudad: "Chía",
    habilidades_que_desarrolla: ["diseño instruccional", "formación", "educación inclusiva", "comunicación"],
    roles_que_habilita: ["Arquitecto del Aprendizaje", "Diseñador Instruccional", "Líder de Formación"],
    prerequisitos: [],
    cupos_disponibles: 16,
    proxima_fecha_inicio: "2026-08-26",
    categoria: "Liderazgo y gestión de personas",
    palabras_clave: ["dua", "aprendizaje", "inclusión", "formación"],
    activo: true,
  },
];
