// ============================================================
// Campus Pass by VinkU — Catálogo mock (dev / fallback)
// 15 cursos verosímiles de instituciones colombianas.
// Se usa cuando la tabla `courses` de Supabase aún no tiene
// cursos Campus Pass cargados. Cubre las 5 categorías objetivo.
// ============================================================

import type { Curso } from "../types/etapa1";

export const CATALOGO_MOCK: Curso[] = [
  // ---- Universidades (5) ----
  {
    id_curso: "cp-upb-01",
    institucion: "Universidad Pontificia Bolivariana",
    tipo_institucion: "universidad",
    nombre_curso: "Especialización en Gerencia de Proyectos",
    nivel: "especializacion",
    modalidad: "hibrida",
    duracion_horas: 240,
    duracion_semanas: 24,
    precio_publico_cop: 9800000,
    precio_vinku_cop: 7200000,
    descuento_disponible: true,
    ciudad: "Medellín",
    habilidades_que_desarrolla: ["gestión de proyectos", "liderazgo", "planeación estratégica"],
    roles_que_habilita: ["Líder de Proyecto", "Gerente de Proyecto", "Coordinador de equipo"],
    prerequisitos: ["Pregrado culminado"],
    cupos_disponibles: 12,
    proxima_fecha_inicio: "2026-08-15",
    categoria: "Liderazgo y gestión de personas",
    palabras_clave: ["pmp", "proyectos", "gerencia", "liderazgo"],
    activo: true,
  },
  {
    id_curso: "cp-eafit-01",
    institucion: "Universidad EAFIT",
    tipo_institucion: "universidad",
    nombre_curso: "Diplomado en Analítica de Datos para Negocios",
    nivel: "diplomado",
    modalidad: "virtual",
    duracion_horas: 120,
    duracion_semanas: 12,
    precio_publico_cop: 4500000,
    precio_vinku_cop: 3100000,
    descuento_disponible: true,
    ciudad: "Medellín",
    habilidades_que_desarrolla: ["datos", "analítica", "excel avanzado", "power bi"],
    roles_que_habilita: ["Analista de Datos", "Analista de Negocio"],
    prerequisitos: [],
    cupos_disponibles: 25,
    proxima_fecha_inicio: "2026-07-20",
    categoria: "Tecnología y sistemas",
    palabras_clave: ["datos", "analytics", "bi", "sql"],
    activo: true,
  },
  {
    id_curso: "cp-unisabana-01",
    institucion: "Universidad de La Sabana",
    tipo_institucion: "universidad",
    nombre_curso: "Diplomado en Gestión Humana Estratégica",
    nivel: "diplomado",
    modalidad: "hibrida",
    duracion_horas: 100,
    duracion_semanas: 10,
    precio_publico_cop: 3800000,
    precio_vinku_cop: 2600000,
    descuento_disponible: true,
    ciudad: "Bogotá",
    habilidades_que_desarrolla: ["gestión de personas", "liderazgo", "comunicación", "clima organizacional"],
    roles_que_habilita: ["Coordinador de Talento", "Gestor de Personas", "Business Partner"],
    prerequisitos: [],
    cupos_disponibles: 18,
    proxima_fecha_inicio: "2026-08-01",
    categoria: "Liderazgo y gestión de personas",
    palabras_clave: ["rrhh", "talento", "gestión humana"],
    activo: true,
  },
  {
    id_curso: "cp-poli-01",
    institucion: "Politécnico Grancolombiano",
    tipo_institucion: "universidad",
    nombre_curso: "Diplomado en Marketing Digital y Growth",
    nivel: "diplomado",
    modalidad: "virtual",
    duracion_horas: 96,
    duracion_semanas: 12,
    precio_publico_cop: 3200000,
    precio_vinku_cop: 2100000,
    descuento_disponible: true,
    ciudad: "Bogotá",
    habilidades_que_desarrolla: ["marketing", "growth", "seo", "publicidad digital", "comunicación"],
    roles_que_habilita: ["Estratega de Marca", "Growth Marketer", "Coordinador de Marketing"],
    prerequisitos: [],
    cupos_disponibles: 30,
    proxima_fecha_inicio: "2026-07-15",
    categoria: "Marketing y ventas",
    palabras_clave: ["marketing", "growth", "seo", "marca"],
    activo: true,
  },
  {
    id_curso: "cp-unal-01",
    institucion: "Universidad Nacional de Colombia",
    tipo_institucion: "universidad",
    nombre_curso: "Curso de Finanzas Corporativas Aplicadas",
    nivel: "educacion_continua",
    modalidad: "presencial",
    duracion_horas: 80,
    duracion_semanas: 8,
    precio_publico_cop: 2900000,
    precio_vinku_cop: 1950000,
    descuento_disponible: true,
    ciudad: "Bogotá",
    habilidades_que_desarrolla: ["finanzas", "análisis financiero", "datos", "presupuesto"],
    roles_que_habilita: ["Analista Financiero", "Coordinador Administrativo y Financiero"],
    prerequisitos: ["Conocimientos básicos de contabilidad"],
    cupos_disponibles: 15,
    proxima_fecha_inicio: "2026-09-01",
    categoria: "Gestión administrativa y finanzas",
    palabras_clave: ["finanzas", "contabilidad", "presupuesto"],
    activo: true,
  },

  // ---- Educación continua / diplomados (5) ----
  {
    id_curso: "cp-ec-01",
    institucion: "Cámara de Comercio de Medellín",
    tipo_institucion: "IETDH",
    nombre_curso: "Programa de Liderazgo de Equipos de Alto Desempeño",
    nivel: "educacion_continua",
    modalidad: "hibrida",
    duracion_horas: 60,
    duracion_semanas: 8,
    precio_publico_cop: 1800000,
    precio_vinku_cop: 1200000,
    descuento_disponible: true,
    ciudad: "Medellín",
    habilidades_que_desarrolla: ["liderazgo", "gestión de personas", "comunicación", "trabajo en equipo"],
    roles_que_habilita: ["Líder de Equipo", "Coordinador", "Jefe de Área"],
    prerequisitos: [],
    cupos_disponibles: 22,
    proxima_fecha_inicio: "2026-07-10",
    categoria: "Liderazgo y gestión de personas",
    palabras_clave: ["liderazgo", "equipos", "management"],
    activo: true,
  },
  {
    id_curso: "cp-ec-02",
    institucion: "SENA — Servicio Nacional de Aprendizaje",
    tipo_institucion: "tecnica",
    nombre_curso: "Curso de Excel y Herramientas Ofimáticas para el Trabajo",
    nivel: "educacion_continua",
    modalidad: "virtual",
    duracion_horas: 48,
    duracion_semanas: 6,
    precio_publico_cop: 900000,
    precio_vinku_cop: 620000,
    descuento_disponible: true,
    ciudad: "Bucaramanga",
    habilidades_que_desarrolla: ["digitales", "excel", "ofimática", "datos"],
    roles_que_habilita: ["Auxiliar Administrativo", "Asistente de Datos"],
    prerequisitos: [],
    cupos_disponibles: 40,
    proxima_fecha_inicio: "2026-07-05",
    categoria: "Gestión administrativa y finanzas",
    palabras_clave: ["excel", "ofimática", "digital"],
    activo: true,
  },
  {
    id_curso: "cp-ec-03",
    institucion: "Cámara de Comercio de Bogotá",
    tipo_institucion: "IETDH",
    nombre_curso: "Diplomado en Ventas Consultivas B2B",
    nivel: "diplomado",
    modalidad: "virtual",
    duracion_horas: 72,
    duracion_semanas: 9,
    precio_publico_cop: 2400000,
    precio_vinku_cop: 1600000,
    descuento_disponible: true,
    ciudad: "Bogotá",
    habilidades_que_desarrolla: ["ventas", "comunicación", "negociación", "marketing"],
    roles_que_habilita: ["Ejecutivo de Ventas", "Consultor Comercial", "Estratega de Marca"],
    prerequisitos: [],
    cupos_disponibles: 20,
    proxima_fecha_inicio: "2026-08-12",
    categoria: "Marketing y ventas",
    palabras_clave: ["ventas", "comercial", "b2b"],
    activo: true,
  },
  {
    id_curso: "cp-ec-04",
    institucion: "Consejo Colombiano de Seguridad",
    tipo_institucion: "IETDH",
    nombre_curso: "Diplomado en Sistema de Gestión de Seguridad y Salud en el Trabajo",
    nivel: "diplomado",
    modalidad: "virtual",
    duracion_horas: 120,
    duracion_semanas: 12,
    precio_publico_cop: 2100000,
    precio_vinku_cop: 1400000,
    descuento_disponible: true,
    ciudad: "Bogotá",
    habilidades_que_desarrolla: ["SST", "seguridad laboral", "normatividad", "gestión de riesgos"],
    roles_que_habilita: ["Coordinador SST", "Analista de Seguridad y Salud en el Trabajo"],
    prerequisitos: [],
    cupos_disponibles: 28,
    proxima_fecha_inicio: "2026-07-25",
    categoria: "Salud ocupacional y SST",
    palabras_clave: ["sst", "seguridad", "salud ocupacional"],
    activo: true,
  },
  {
    id_curso: "cp-ec-05",
    institucion: "EAN — Universidad EAN",
    tipo_institucion: "universidad",
    nombre_curso: "Curso de Diseño de Programas de Formación Corporativa",
    nivel: "educacion_continua",
    modalidad: "virtual",
    duracion_horas: 64,
    duracion_semanas: 8,
    precio_publico_cop: 2600000,
    precio_vinku_cop: 1750000,
    descuento_disponible: true,
    ciudad: "Bogotá",
    habilidades_que_desarrolla: ["diseño instruccional", "formación", "comunicación", "gestión de personas"],
    roles_que_habilita: ["Arquitecto del Aprendizaje", "Diseñador Instruccional", "Líder de Formación"],
    prerequisitos: [],
    cupos_disponibles: 16,
    proxima_fecha_inicio: "2026-08-20",
    categoria: "Liderazgo y gestión de personas",
    palabras_clave: ["formación", "aprendizaje", "diseño instruccional"],
    activo: true,
  },

  // ---- Técnicos (3) ----
  {
    id_curso: "cp-tec-01",
    institucion: "CENDI — Centro de Desarrollo Informático",
    tipo_institucion: "tecnica",
    nombre_curso: "Técnico Laboral en Desarrollo Web Full Stack",
    nivel: "tecnico_laboral",
    modalidad: "presencial",
    duracion_horas: 320,
    duracion_semanas: 20,
    precio_publico_cop: 3600000,
    precio_vinku_cop: 2400000,
    descuento_disponible: true,
    ciudad: "Medellín",
    habilidades_que_desarrolla: ["programación", "digitales", "desarrollo web", "javascript"],
    roles_que_habilita: ["Desarrollador Web", "Programador Junior", "Tech sin Título"],
    prerequisitos: [],
    cupos_disponibles: 14,
    proxima_fecha_inicio: "2026-08-05",
    categoria: "Tecnología y sistemas",
    palabras_clave: ["programación", "web", "fullstack", "tech"],
    activo: true,
  },
  {
    id_curso: "cp-tec-02",
    institucion: "Politécnico de Colombia",
    tipo_institucion: "tecnica",
    nombre_curso: "Técnico Laboral en Asistencia Administrativa",
    nivel: "tecnico_laboral",
    modalidad: "hibrida",
    duracion_horas: 280,
    duracion_semanas: 18,
    precio_publico_cop: 2200000,
    precio_vinku_cop: 1500000,
    descuento_disponible: true,
    ciudad: "Medellín",
    habilidades_que_desarrolla: ["administración", "ofimática", "digitales", "gestión documental"],
    roles_que_habilita: ["Auxiliar Administrativo", "Asistente Administrativo", "Primera Carrera Real"],
    prerequisitos: [],
    cupos_disponibles: 26,
    proxima_fecha_inicio: "2026-07-18",
    categoria: "Gestión administrativa y finanzas",
    palabras_clave: ["administración", "asistente", "oficina"],
    activo: true,
  },
  {
    id_curso: "cp-tec-03",
    institucion: "Politécnico de Colombia",
    tipo_institucion: "tecnica",
    nombre_curso: "Curso Técnico en Soporte y Redes",
    nivel: "tecnico_profesional",
    modalidad: "presencial",
    duracion_horas: 200,
    duracion_semanas: 16,
    precio_publico_cop: 2800000,
    precio_vinku_cop: 1900000,
    descuento_disponible: true,
    ciudad: "Bucaramanga",
    habilidades_que_desarrolla: ["redes", "soporte técnico", "digitales", "hardware"],
    roles_que_habilita: ["Técnico de Soporte", "Analista de Mesa de Ayuda", "Tech sin Título"],
    prerequisitos: [],
    cupos_disponibles: 12,
    proxima_fecha_inicio: "2026-09-10",
    categoria: "Tecnología y sistemas",
    palabras_clave: ["redes", "soporte", "ti"],
    activo: true,
  },

  // ---- Sin descuento — Caso B (2) ----
  {
    id_curso: "cp-b-01",
    institucion: "Universidad de los Andes",
    tipo_institucion: "universidad",
    nombre_curso: "Programa Avanzado de Estrategia y Liderazgo Ejecutivo",
    nivel: "educacion_continua",
    modalidad: "presencial",
    duracion_horas: 90,
    duracion_semanas: 10,
    precio_publico_cop: 7500000,
    precio_vinku_cop: 0,
    descuento_disponible: false,
    ciudad: "Bogotá",
    habilidades_que_desarrolla: ["liderazgo", "estrategia", "gestión de personas", "planeación estratégica"],
    roles_que_habilita: ["Director", "Gerente General", "Líder de Proyecto"],
    prerequisitos: ["5+ años de experiencia"],
    cupos_disponibles: 10,
    proxima_fecha_inicio: "2026-09-15",
    categoria: "Liderazgo y gestión de personas",
    palabras_clave: ["estrategia", "liderazgo", "ejecutivo"],
    activo: true,
  },
  {
    id_curso: "cp-b-02",
    institucion: "Universidad ICESI",
    tipo_institucion: "universidad",
    nombre_curso: "Diplomado en Transformación Digital de Negocios",
    nivel: "diplomado",
    modalidad: "virtual",
    duracion_horas: 110,
    duracion_semanas: 11,
    precio_publico_cop: 4200000,
    precio_vinku_cop: 0,
    descuento_disponible: false,
    ciudad: "Cali",
    habilidades_que_desarrolla: ["transformación digital", "datos", "digitales", "innovación"],
    roles_que_habilita: ["Líder de Transformación Digital", "Analista de Negocio"],
    prerequisitos: [],
    cupos_disponibles: 20,
    proxima_fecha_inicio: "2026-08-25",
    categoria: "Tecnología y sistemas",
    palabras_clave: ["transformación digital", "innovación", "negocios"],
    activo: true,
  },
];
