-- Generado por scripts/ingesta-dane/3-generar-sql.ts (propuesta REVISADA).
-- 144 habilidades aprobadas. ON CONFLICT (name) DO NOTHING.

insert into skills (name, skill_type, source_reference) values
  ('Acuicultura y pesca', 'hard', 'CUOC 2025 · DANE conocimiento #83'),
  ('Adquisición del lenguaje', 'hard', 'CUOC 2025 · DANE conocimiento #52'),
  ('Análisis de control de calidad', 'soft', 'CUOC 2025 · DANE destreza #22'),
  ('Análisis de necesidades', 'soft', 'CUOC 2025 · DANE destreza #17'),
  ('Análisis de procesos', 'soft', 'CUOC 2025 · DANE destreza #27'),
  ('Anatomía', 'hard', 'CUOC 2025 · DANE conocimiento #40'),
  ('Aprendizaje aplicado', 'soft', 'CUOC 2025 · DANE destreza #7'),
  ('Armonía y composición', 'hard', 'CUOC 2025 · DANE conocimiento #46'),
  ('Arquitectura y urbanismo', 'hard', 'CUOC 2025 · DANE conocimiento #53'),
  ('Artesanías', 'hard', 'CUOC 2025 · DANE conocimiento #54'),
  ('Atención a adultos, adultos mayores con o sin discapacidad', 'hard', 'CUOC 2025 · DANE conocimiento #55'),
  ('Atención integral en salud', 'hard', 'CUOC 2025 · DANE conocimiento #49'),
  ('Atención, protección y servicios a la infancia, adolescencia y juventud', 'hard', 'CUOC 2025 · DANE conocimiento #42'),
  ('Bellas artes', 'hard', 'CUOC 2025 · DANE conocimiento #24'),
  ('Bibliotecología, información y archivología', 'hard', 'CUOC 2025 · DANE conocimiento #56'),
  ('Biología', 'hard', 'CUOC 2025 · DANE conocimiento #17'),
  ('Bioquímica', 'hard', 'CUOC 2025 · DANE conocimiento #57'),
  ('Cadena de suministro', 'hard', 'CUOC 2025 · DANE conocimiento #100'),
  ('Ciencias de la tierra', 'hard', 'CUOC 2025 · DANE conocimiento #58'),
  ('Ciencias del medio ambiente', 'hard', 'CUOC 2025 · DANE conocimiento #59'),
  ('Ciencias políticas y educación cívica', 'hard', 'CUOC 2025 · DANE conocimiento #60'),
  ('Comprensión de lectura', 'soft', 'CUOC 2025 · DANE destreza #1'),
  ('Computadoras, electrónica y automatización', 'hard', 'CUOC 2025 · DANE conocimiento #9'),
  ('Comunicación asertiva', 'soft', 'CUOC 2025 · DANE destreza #4'),
  ('Conciliación', 'soft', 'CUOC 2025 · DANE destreza #13'),
  ('Construcción e ingeniería civil', 'hard', 'CUOC 2025 · DANE conocimiento #12'),
  ('Contabilidad e impuestos', 'hard', 'CUOC 2025 · DANE conocimiento #32'),
  ('Creatividad', 'soft', 'CUOC 2025 · DANE destreza #39'),
  ('Criterio y toma de decisiones', 'soft', 'CUOC 2025 · DANE destreza #28'),
  ('Deportes', 'hard', 'CUOC 2025 · DANE conocimiento #61'),
  ('Derecho', 'hard', 'CUOC 2025 · DANE conocimiento #62'),
  ('Desarrollo y análisis de software y aplicaciones', 'hard', 'CUOC 2025 · DANE conocimiento #63'),
  ('Diseño', 'hard', 'CUOC 2025 · DANE conocimiento #11'),
  ('Diseño de tecnología', 'soft', 'CUOC 2025 · DANE destreza #18'),
  ('Diseño industrial, de moda e interiores', 'hard', 'CUOC 2025 · DANE conocimiento #64'),
  ('Diseño y administración de redes y bases de datos', 'hard', 'CUOC 2025 · DANE conocimiento #65'),
  ('Economía', 'hard', 'CUOC 2025 · DANE conocimiento #3'),
  ('Educación militar y de defensa', 'hard', 'CUOC 2025 · DANE conocimiento #66'),
  ('Educación y capacitación', 'hard', 'CUOC 2025 · DANE conocimiento #22'),
  ('Ejecución instrumental', 'hard', 'CUOC 2025 · DANE conocimiento #47'),
  ('Electricidad y energía', 'hard', 'CUOC 2025 · DANE conocimiento #67'),
  ('Enfermería', 'hard', 'CUOC 2025 · DANE conocimiento #68'),
  ('Ensamble', 'soft', 'CUOC 2025 · DANE destreza #36'),
  ('Escucha activa', 'soft', 'CUOC 2025 · DANE destreza #2'),
  ('Estadística', 'hard', 'CUOC 2025 · DANE conocimiento #69'),
  ('Estrategias para el aprendizaje', 'soft', 'CUOC 2025 · DANE destreza #8'),
  ('Evaluación y control de actividades', 'soft', 'CUOC 2025 · DANE destreza #9'),
  ('Farmacia', 'hard', 'CUOC 2025 · DANE conocimiento #70'),
  ('Filosofía y ética', 'hard', 'CUOC 2025 · DANE conocimiento #26'),
  ('Física', 'hard', 'CUOC 2025 · DANE conocimiento #15'),
  ('Fisioterapia, fonoaudiología, terapia ocupacional, nutrición y afines', 'hard', 'CUOC 2025 · DANE conocimiento #71'),
  ('Flexibilidad y adaptabilidad', 'soft', 'CUOC 2025 · DANE destreza #35'),
  ('Geografía y territorio', 'hard', 'CUOC 2025 · DANE conocimiento #20'),
  ('Gerencia y administración', 'hard', 'CUOC 2025 · DANE conocimiento #1'),
  ('Gestión de recursos financieros', 'soft', 'CUOC 2025 · DANE destreza #30'),
  ('Gestión de recursos materiales', 'soft', 'CUOC 2025 · DANE destreza #31'),
  ('Gestión del riesgo de desastres', 'hard', 'CUOC 2025 · DANE conocimiento #45'),
  ('Gestión del talento humano y de personal', 'hard', 'CUOC 2025 · DANE conocimiento #6'),
  ('Gestión del Talento Humano y de Personal', 'soft', 'CUOC 2025 · DANE destreza #32'),
  ('Gestión del tiempo', 'soft', 'CUOC 2025 · DANE destreza #29'),
  ('Gestión financiera, administración bancaria y seguros', 'hard', 'CUOC 2025 · DANE conocimiento #33'),
  ('Herramientas de simulación y diseño', 'hard', 'CUOC 2025 · DANE conocimiento #34'),
  ('Historia y arqueología', 'hard', 'CUOC 2025 · DANE conocimiento #25'),
  ('Horticultura (técnicas de huertas, invernaderos, viveros y jardines)', 'hard', 'CUOC 2025 · DANE conocimiento #72'),
  ('Hotelería, restaurantes y servicios de banquetes', 'hard', 'CUOC 2025 · DANE conocimiento #73'),
  ('Idioma extranjero', 'hard', 'CUOC 2025 · DANE conocimiento #23'),
  ('Ingeniería y procesos químicos', 'hard', 'CUOC 2025 · DANE conocimiento #74'),
  ('Ingeniería y tecnología', 'hard', 'CUOC 2025 · DANE conocimiento #10'),
  ('Instrumentación quirúrgica', 'hard', 'CUOC 2025 · DANE conocimiento #75'),
  ('Instrumentos musicales', 'hard', 'CUOC 2025 · DANE conocimiento #48'),
  ('Interpretación', 'soft', 'CUOC 2025 · DANE destreza #40'),
  ('Interpretación de planos', 'hard', 'CUOC 2025 · DANE conocimiento #35'),
  ('Leyes y gobierno', 'hard', 'CUOC 2025 · DANE conocimiento #28'),
  ('Liderazgo', 'soft', 'CUOC 2025 · DANE destreza #33'),
  ('Literatura y lingüística', 'hard', 'CUOC 2025 · DANE conocimiento #76'),
  ('Lógica matemática', 'soft', 'CUOC 2025 · DANE destreza #5'),
  ('Manejo de imprevistos', 'soft', 'CUOC 2025 · DANE destreza #25'),
  ('Manejo de las TIC', 'hard', 'CUOC 2025 · DANE conocimiento #36'),
  ('Manipulación de alimentos', 'hard', 'CUOC 2025 · DANE conocimiento #37'),
  ('Mantenimiento', 'hard', 'CUOC 2025 · DANE conocimiento #38'),
  ('Mantenimiento de equipos', 'soft', 'CUOC 2025 · DANE destreza #24'),
  ('Matemáticas', 'hard', 'CUOC 2025 · DANE conocimiento #14'),
  ('Materiales (vidrio, papel, plástico y madera)', 'hard', 'CUOC 2025 · DANE conocimiento #77'),
  ('Mecánica e ingeniería de vehículos, barcos y aeronaves de motor', 'hard', 'CUOC 2025 · DANE conocimiento #94'),
  ('Mecánica y metalistería', 'hard', 'CUOC 2025 · DANE conocimiento #13'),
  ('Medicina', 'hard', 'CUOC 2025 · DANE conocimiento #21'),
  ('Medicina y terapia alternativa y complementaria y partería tradicional', 'hard', 'CUOC 2025 · DANE conocimiento #51'),
  ('Medio ambiente natural y vida silvestre', 'hard', 'CUOC 2025 · DANE conocimiento #78'),
  ('Mercadotecnia y publicidad', 'hard', 'CUOC 2025 · DANE conocimiento #4'),
  ('Metodología e investigación', 'hard', 'CUOC 2025 · DANE conocimiento #102'),
  ('Minería y extracción', 'hard', 'CUOC 2025 · DANE conocimiento #79'),
  ('Moda y belleza', 'hard', 'CUOC 2025 · DANE conocimiento #103'),
  ('Música y artes escénicas', 'hard', 'CUOC 2025 · DANE conocimiento #80'),
  ('Odontología y estudios dentales', 'hard', 'CUOC 2025 · DANE conocimiento #81'),
  ('Orientación al servicio', 'soft', 'CUOC 2025 · DANE destreza #15'),
  ('Patrimonio cultural', 'hard', 'CUOC 2025 · DANE conocimiento #43'),
  ('Patrimonio natural', 'hard', 'CUOC 2025 · DANE conocimiento #44'),
  ('Peluquería y tratamientos de belleza', 'hard', 'CUOC 2025 · DANE conocimiento #82'),
  ('Pensamiento crítico', 'soft', 'CUOC 2025 · DANE destreza #6'),
  ('Pensamiento sistémico', 'soft', 'CUOC 2025 · DANE destreza #41'),
  ('Periodismo, comunicación y reportajes', 'hard', 'CUOC 2025 · DANE conocimiento #30'),
  ('Persuasión', 'soft', 'CUOC 2025 · DANE destreza #12'),
  ('Primeros auxilios', 'hard', 'CUOC 2025 · DANE conocimiento #41'),
  ('Principios éticos', 'hard', 'CUOC 2025 · DANE conocimiento #101'),
  ('Proactividad', 'soft', 'CUOC 2025 · DANE destreza #37'),
  ('Procesamiento de alimentos', 'hard', 'CUOC 2025 · DANE conocimiento #8'),
  ('Producción agrícola y pecuaria', 'hard', 'CUOC 2025 · DANE conocimiento #98'),
  ('Producción y procesamiento', 'hard', 'CUOC 2025 · DANE conocimiento #7'),
  ('Productos textiles (ropa, calzado y artículos de cuero)', 'hard', 'CUOC 2025 · DANE conocimiento #84'),
  ('Programación', 'soft', 'CUOC 2025 · DANE destreza #21'),
  ('Química', 'hard', 'CUOC 2025 · DANE conocimiento #16'),
  ('Redacción de textos', 'soft', 'CUOC 2025 · DANE destreza #3'),
  ('Relaciones interpersonales', 'soft', 'CUOC 2025 · DANE destreza #10'),
  ('Religión y teología', 'hard', 'CUOC 2025 · DANE conocimiento #99'),
  ('Reparación', 'soft', 'CUOC 2025 · DANE destreza #26'),
  ('Resolución de problemas complejos', 'soft', 'CUOC 2025 · DANE destreza #16'),
  ('Saneamiento de la comunidad', 'hard', 'CUOC 2025 · DANE conocimiento #86'),
  ('Seguir instrucciones', 'soft', 'CUOC 2025 · DANE destreza #38'),
  ('Seguridad pública', 'hard', 'CUOC 2025 · DANE conocimiento #27'),
  ('Seguridad y salud en el trabajo', 'hard', 'CUOC 2025 · DANE conocimiento #85'),
  ('Selección de equipo', 'soft', 'CUOC 2025 · DANE destreza #19'),
  ('Servicio a la persona y humanización', 'hard', 'CUOC 2025 · DANE conocimiento #50'),
  ('Servicio al cliente', 'hard', 'CUOC 2025 · DANE conocimiento #5'),
  ('Servicios de oficina y administrativos', 'hard', 'CUOC 2025 · DANE conocimiento #2'),
  ('Servicios de transporte', 'hard', 'CUOC 2025 · DANE conocimiento #31'),
  ('Servicios domésticos', 'hard', 'CUOC 2025 · DANE conocimiento #87'),
  ('Servicios funerarios', 'hard', 'CUOC 2025 · DANE conocimiento #88'),
  ('Sicología / psicología', 'hard', 'CUOC 2025 · DANE conocimiento #18'),
  ('Silvicultura y producción forestal', 'hard', 'CUOC 2025 · DANE conocimiento #89'),
  ('Sociología, antropología y estudios culturales', 'hard', 'CUOC 2025 · DANE conocimiento #19'),
  ('Tanatopraxia', 'hard', 'CUOC 2025 · DANE conocimiento #39'),
  ('Técnicas audiovisuales y producción para medios de comunicación', 'hard', 'CUOC 2025 · DANE conocimiento #90'),
  ('Técnicas somáticas y de manejo corporal', 'hard', 'CUOC 2025 · DANE conocimiento #104'),
  ('Tecnología de diagnóstico y tratamiento médico', 'hard', 'CUOC 2025 · DANE conocimiento #91'),
  ('Tecnologías de protección y gestión del medio ambiente', 'hard', 'CUOC 2025 · DANE conocimiento #92'),
  ('Telecomunicación', 'hard', 'CUOC 2025 · DANE conocimiento #29'),
  ('Trabajo bajo presión', 'soft', 'CUOC 2025 · DANE destreza #34'),
  ('Trabajo en equipo', 'soft', 'CUOC 2025 · DANE destreza #11'),
  ('Trabajo social', 'hard', 'CUOC 2025 · DANE conocimiento #93'),
  ('Transmisión de conocimiento', 'soft', 'CUOC 2025 · DANE destreza #14'),
  ('Ventas al por mayor y al por menor', 'hard', 'CUOC 2025 · DANE conocimiento #95'),
  ('Veterinaria', 'hard', 'CUOC 2025 · DANE conocimiento #96'),
  ('Viajes, turismo y actividades recreativas', 'hard', 'CUOC 2025 · DANE conocimiento #97'),
  ('Vigilancia de las operaciones', 'soft', 'CUOC 2025 · DANE destreza #23')
on conflict (name) do nothing;
